# Built application files
*.apk
*.ap_

# Files for the ART/Dalvik VM
*.dex

# Java class files
*.class

# Generated files
bin/
gen/
out/

# Gradle files
.gradle/
build/

# Local configuration file (sdk path, etc)
local.properties

# Proguard folder generated by Eclipse
proguard/

# Log Files
*.log

# Android Studio Navigation editor temp files
.navigation/

# Android Studio captures folder
captures/

# Intellij
*.iml
.idea/workspace.xml
.idea/libraries

# Keystore files
*.jks

# External native build folder generated in Android Studio 2.2 and later
.externalNativeBuild
.idea/file.template.settings.xml
.idea/libraries/
4: splash.png
ComplaintAction.png
Fullerton Last Transaction.png
Fullerton Last transaction dashboard.png
Not you.png
RootShell/
RootTools/
Screenshot/
app/Fullerton.apk
app/fabric.properties
app/google-services-old.json
app/keystore/
app/src/main/jniLibs/
app/src/main/res/values-v17/
app/src/main/java/test/TestActivity/
complaint_comment_dialog.png
databiding/libs/
databiding/src/main/res/drawable/
device-2016-07-15-154415.png
fileProvider/
import-summary.txt
keystore/
projectFilesBackup/
reactivetutorial/libs/
reactivetutorial/src/main/res/drawable/
sms/libs/
sms/src/main/res/drawable/
socialauthandroid 3.2/libs/
socialauthandroid 3.2/lint.xml
socialauthandroid 3.2/src/
.gradle/2.14.1/tasks/
